### ISSUE TITLE
詳細画面で何を作るかを決める

### ISSUE THREAD

**Issue by penicillin0** [penicillin0/devotion#21]
## Why & What

ref. https://github.com/penicillin0/devotion/issues/20 

詳細画面として何をどの順序で実装するかを決めたい。

### 実装順番
- Phase 1
    * [問題文が見える](https://github.com/penicillin0/devotion/issues/21#issuecomment-654784047)
        + たぶん簡単
- Phase 2
    * [解答状況がわかる](https://github.com/penicillin0/devotion/issues/21#issuecomment-654788879)
        + ちょっと大変
- Phase X
   * [ジャンル](https://github.com/penicillin0/devotion/issues/21#issuecomment-654791577)
       + とりあえずpass

**Comment by kdnk** [comment]
## aaa

**Comment by kdnk** [comment]
- [ ] aaaaaaA https://github.com/penicillin0/devotion/issues/20

**Comment by penicillin0** [comment]
### とりあえず欲しい機能列挙
- 問題文が見える
- 解答状況がわかる
    * 解答ステータス
    * 提出時間

**Comment by penicillin0** [comment]
## 順番
- Phase 1
    * 問題文のみ
- Phase 2
   * 解答状況がわかる
        + 解答ステータス
        + 提出時刻
- Phase 3
    * 点数
    * 本番の正答率
- Phase 5
    * 問題のジャンル

**Comment by penicillin0** [comment]
## 問題文が見える
- 事前に問題文をFirestoreに入れておく
    * Firestoreにデータを入れる際は手元でスクレイピングする感じ
- Hostingの際にFireStoreから該当する問題文を取ってくるようにする
    * ProblemItemコンポーネント内

**Comment by penicillin0** [comment]
## 解答状況がわかる

### detail
- 解答状況がわかる
    * 解答ステータス
        + AC, WA, TLE...
    * 提出時刻

### 実装方法
- アカウント名が分かれば、提出した問題が全部わかる
    * https://github.com/kenkoooo/AtCoderProblems/blob/master/doc/api.md#user-submissions
    * 1リクエスト/ 分 
        + https://github.com/kenkoooo/AtCoderProblems/blob/master/doc/api.md#caution
- このレスポンスに問題名でfilterかける
    * 時間でソート
    * 古い順に表示

**Comment by penicillin0** [comment]
## 点数

### 点数いるかな？？？？
- AOJが点数がないからあっても微妙な気がする
- そもそも水色になるための100問なわけだし、点数はあまり気にならない？

**Comment by penicillin0** [comment]
## ジャンル

- そもそも問題にジャンルが設定されているわけではないので、かなり難しい
- Qiitaでは簡単にジャンル分けされているので、それを流用するのあり？

- メリット
    * 解き方が予想できる
    * 自分の苦手に狙い撃ちできる
- デメリット
    * 解き方が予想できてしまう
    * 思考にバイアスがかかる (別解とか思いつきにくい)

**Comment by penicillin0** [comment]
決まったのでClose
https://github.com/penicillin0/devotion/issues/21#issue-652225116
